# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUeFqd0MLK3BLu-GwptiGN2EXg5zocaE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn
from google.colab import files

df = pd.read_csv('/content/Project Management Dataset.csv')
#print(df.head())
#print(df.head())
#print(df.tail())
#print(df.dtypes)
#print(df.isnull().sum())
#print(df.describe())

# seaborn.histplot(data=df,x=' Project Cost ',kde=True)
# plt.title('Distribution of Project Costs')
# plt.show()

# seaborn.countplot(data=df,x='Project Type')
# plt.xticks(rotation=45)
# plt.title('Project Count by Type')
# plt.show()

# seaborn.barplot(data=df,x='Department', y=' Project Cost ', estimator=np.mean)
# plt.xticks(rotation=45)
# plt.title('Average Cost by Department')
# plt.show()

# plt.pie(df['Status'].value_counts(),labels=df['Status'].value_counts().index,autopct='%1.1f%%' )
# plt.title('Project Status Distribution')
# plt.show()

# corr = df.corr()
# seaborn.heatmap(corr,annot=True, cmap='coolwarm')
# plt.title('Correlation Heatmap')
# plt.show()

# seaborn.boxplot(data=df,x='Complexity',y='Completion%',showfliers=False)
# plt.title('Project Completion % by Complexity')
# plt.show()

df[' Project Cost '] = df[' Project Cost '].str.replace(',', '').astype(float)



# df['Year-Month']=df['Year'].astype(str) + '-' + df['Month'].astype(str)
# df.groupby('Year-Month')[' Project Cost '].sum().plot()
# plt.title('Monthly Project Costs Over Time ')
# plt.Xticks(rotation=45)
# plt.show()

# seaborn.scatterplot(data = df,x=' Project Cost ',y=' Project Benefit ')
# plt.title('Project Cost vs. Benefit')
# plt.show()


# import plotly.express as px

# fig = px.scatter_3d(df, x=' Project Cost ', y=' Project Benefit ', z='Complexity',
#                   color='Project Type')
# fig.update_layout(scene = dict(
#                     xaxis = dict(title  = 'Project Cost'),
#                     yaxis = dict(title  = 'Project Benefit'),
#                     zaxis = dict(title  = 'Complexity')))
# fig.show()

from google.colab import drive
drive.mount('/content/drive')